### ISSUE TITLE
Temperature output is always -1

### ISSUE THREAD

**Issue by desinox** [orangecoding/homebridge-influx#1]
Hi, 
I tried to enter the scheme as described on the node-influx page you link, unfortunately I still get -1 as temperature output. Could someone therefore briefly tell me how to convert a flux query (with filters) so that the correct field is recognized as temperature value?
I hope you can help me,
Simon

**Comment by orangecoding** [comment]
You actually don't need to write a flux query. The example should show you that you only need to configure where to find the field. 

If it returns -1, are you sure the field itself is not set to -1?

**Comment by orangecoding** [comment]
Closed due to no response whatsoever

**Comment by snieht** [comment]
Hi Orangecoding,
i do think i got the same issue.
It returns -1 for Temperature; humidity = 0.
In Grafana i see realistic Measures. (11.5° and 47.5%).

any Idea? Would be greatful for your help. Gern auch pm auf deutsch wenn es hilft ;)

"[2022-4-30 21:43:07] [homebridge-influx] This plugin threw an error from the characteristic 'Current Temperature': Unhandled error thrown inside read handler for characteristic: Cannot read property 'field' of undefined. See https://homebridge.io/w/JtMGR for more info."
